
title: Ueslei Sutil
url: 'http://uesleisutil.github.io'
baseurl: 'uesleisutil.github.io' #change it according to your repository name

# Profile information
yourname: Ueslei Sutil  ## put your name
title: 'OCEANOGRAPHER'  ## your title
location: São José dos Campos, SP, Brazil


## Social Profiles
facebook: https://www.facebook.com/uesleisutil  ## your facebook account url
linkedin: https://www.linkedin.com/in/usutil/  ## your linkedin account url
instagram: https://www.instagram.com/uesleisutil/
github: https://github.com/uesleisutil
researchgate: https://www.researchgate.net/profile/Ueslei_Sutil
# Update all the sections by editing the files inside _includes folder.
