
title: Ueslei Sutil
url: 'http://uesleisutil.github.io'
baseurl: 'uesleisutil.github.io' #change it according to your repository name

# Profile information
yourname: Ueslei Sutil  ## put your name
title: 'OCEANOGRAPHER'  ## your title
location: São José dos Campos, SP, Brazil


## Social Profiles
instagram: https://www.instagram.com/uesleisutil/
linkedin: https://www.linkedin.com/in/usutil/  ## your linkedin account url
github: https://github.com/uesleisutil
researchgate: https://www.researchgate.net/profile/Ueslei_Sutil
lattes:  http://lattes.cnpq.br/7449952079999911
# Update all the sections by editing the files inside _includes folder.
